require('./signUpTest');
require('./loginTest');
require('./updateProfileTest');
require('./updatePointsTest');
require('./refreshTokenTest');
require('./verifyTokenTest');
require('./getLeaderBoardTest');
require('./getProfileTest');
require('./getHistoryTest');
