version: '3.8'

services:
  socketservice:
    build: ./SocketService
    restart: unless-stopped
    ports:
      - 3030:3030
    command: node ./index.js
    depends_on:
      - userservice
      - gameservice
  userservice:
    build: ./UserService
    restart: unless-stopped
    ports:
      - 3031:3031
    command: node ./index.js
  gameservice:
    build: ./GameService
    restart: unless-stopped
    ports:
      - 3032:3032
    command: node ./index.js
