services:
  gameservice:
    container_name: gameservice
    image: registry.digitalocean.com/checkers-cr/checkers:gameservice
    build: 
      context: ./Backend/Checkers-GameService
      args:
        - ARG_PORT=${GameService_PORT}
        - ARG_DB_PSW=${DB_PSW}
        - ARG_GAME_KEY=${GAME_KEY}
        - ARG_GAME_CERT=${GAME_CERT}
        - ARG_CERTIFICATE=${CERTIFICATE}
    restart: always
    ports:
      - ${GameService_PORT}:${GameService_PORT}
      
  userservice:
    container_name: userservice
    image: registry.digitalocean.com/checkers-cr/checkers:userservice
    build: 
      context: ./Backend/Checkers-UserService
      args:
        - ARG_PORT=${UserService_PORT}
        - ARG_DB_PSW=${DB_PSW}
        - ARG_USER_KEY=${USER_KEY}
        - ARG_USER_CERT=${USER_CERT}
        - ARG_CERTIFICATE=${CERTIFICATE}
    restart: always
    ports:
      - ${UserService_PORT}:${UserService_PORT}
  
  communicationservice:
    container_name: communicationservice
    image: registry.digitalocean.com/checkers-cr/checkers:communicationservice
    build: 
      context: ./Backend/Checkers-CommunicationService
      args:
        - ARG_PORT=${CommunicationService_PORT}
        - ARG_USERSERVICE_PORT=${UserService_PORT}
        - ARG_GAMESERVICE_PORT=${GameService_PORT}
        - ARG_DB_PSW=${DB_PSW}
        - ARG_COMM_KEY=${COMM_KEY}
        - ARG_COMM_CERT=${COMM_CERT}
        - ARG_GAME_KEY=${GAME_KEY}
        - ARG_GAME_CERT=${GAME_CERT}
        - ARG_USER_KEY=${USER_KEY}
        - ARG_USER_CERT=${USER_CERT}
        - ARG_CERTIFICATE=${CERTIFICATE}
        - ARG_USER_SERVICE=${USER_SERVICE}
        - ARG_GAME_SERVICE=${GAME_SERVICE}
    restart: always
    ports:
      - ${CommunicationService_PORT}:${CommunicationService_PORT}

  frontend:
    container_name: frontend
    image: registry.digitalocean.com/checkers-cr/checkers:frontend
    build: 
      context: ./Frontend/Checkers-Frontend
      args:
        - ARG_VUE_APP_COMMUNICATION_SERVICE=${VUE_APP_COMMUNICATION_SERVICE}
    restart: always
    ports:
      - 8000:80