version: '3.8'

services:
  socketservice:
    build: ./Backend/SocketService
    restart: unless-stopped
    ports:
      - 3030:3030
    command: node ./Backend/index.js
    depends_on:
      - userservice
      - gameservice
  userservice:
    build: ./Backend/UserService
    restart: unless-stopped
    ports:
      - 3031:3031
    command: node ./Backend/index.js
  gameservice:
    build: ./Backend/GameService
    restart: unless-stopped
    ports:
      - 3032:3032
    command: node ./Backend/index.js
  playerservice1:
    build: ./Frontend
    command: npm run serve -- --port 3000
    restart: unless-stopped
    ports:
      - 3000:3000
  playerservice2:
    build: ./Frontend
    command: npm run serve -- --port 3001
    restart: unless-stopped
    ports:
      - 3001:3001
  playerservice3:
    build: ./Frontend
    command: npm run serve -- --port 3002
    restart: unless-stopped
    ports:
      - 3002:3002
